import type { LocaleStrings } from './types';

interface Locales {
  en: LocaleStrings;
  zh: LocaleStrings;
}

export const locales: Locales = {
  en: {
    appTitle: "Gemini Reminder Service",
    pendingReminders: "Reminders",
    addReminder: "Add New Reminder",
    reminderTitle: "Title",
    reminderContent: "Content",
    dueDate: "Due Date",
    telegramRecipientId: "Telegram Recipient ID",
    telegramRecipientIdPlaceholder: "e.g., 123456789 or @mychannel",
    telegramRecipientIdHint: "User ID (get from @userinfobot), Group ID (starts with -), or public Channel username.",
    submit: "Add Reminder",
    delete: "Delete",
    noReminders: "No pending reminders. Add one to get started!",
    footerText: "Powered by Gemini & React",
    telegramBotToken: "Telegram Bot Token",
    setToken: "Save Token",
    tokenSaved: "Token saved successfully!",
    tokenNotSetWarning: "Bot token is not set. Notifications will not be sent.",
    tokenInfo: "Your token is stored locally in your browser and is never sent to any server except Telegram.",
    showToken: "Show",
    hideToken: "Hide",
    statusPending: "Pending",
    statusSent: "Sent",
    statusFailed: "Failed",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    retry: "Retry",
    filterAll: "All",
    filterPending: "Pending",
    filterSent: "Sent",
    filterFailed: "Failed",
    tags: "Tags",
    tagsPlaceholder: "e.g. work, life, domain",
    filterByTag: "Filter by tag",
    allTags: "All Tags",
    importFromExcel: "Import from Excel",
    remindersImportedSuccess: "reminders imported successfully!",
    downloadTemplate: "Download Template",
  },
  zh: {
    appTitle: "Telegram 机器人提醒服务",
    pendingReminders: "提醒列表",
    addReminder: "添加新提醒",
    reminderTitle: "标题",
    reminderContent: "内容",
    dueDate: "截止日期",
    telegramRecipientId: "Telegram 接收者ID",
    telegramRecipientIdPlaceholder: "例如 123456789 或 @mychannel",
    telegramRecipientIdHint: "用户ID (可从 @userinfobot 获取)、群组ID (以 - 开头) 或公共频道用户名。",
    submit: "添加提醒",
    delete: "删除",
    noReminders: "没有待处理的提醒。请添加一个新提醒！",
    footerText: "由 Gemini 和 React 驱动",
    telegramBotToken: "Telegram 机器人令牌",
    setToken: "保存令牌",
    tokenSaved: "令牌保存成功！",
    tokenNotSetWarning: "机器人令牌未设置，将无法发送通知。",
    tokenInfo: "您的令牌存储在本地浏览器中，除了 Telegram 之外，不会发送到任何服务器。",
    showToken: "显示",
    hideToken: "隐藏",
    statusPending: "待处理",
    statusSent: "已发送",
    statusFailed: "发送失败",
    edit: "编辑",
    save: "保存",
    cancel: "取消",
    retry: "重试",
    filterAll: "全部",
    filterPending: "待处理",
    filterSent: "已发送",
    filterFailed: "失败",
    tags: "标签",
    tagsPlaceholder: "例如 工作, 生活, 域名",
    filterByTag: "按标签筛选",
    allTags: "所有标签",
    importFromExcel: "从 Excel 导入",
    remindersImportedSuccess: "个提醒导入成功！",
    downloadTemplate: "下载模板",
  },
};